### ISSUE TITLE
Add dedicated BrowserNavigate action

### ISSUE THREAD

**Issue by jeffreylsoffer** [bitfocus/companion-module-studiocoast-vmix#104]
**Describe the feature**
Add a dedicated action for BrowserNavigate to avoid URL Encoding funkiness.

**Is this version dependent (vMix v24.)?**
No

**Usecases**
I have a bunch of custom BrowserNavigate commands on buttons to change from various setups (testing vs production) and it's always really tricky to get the url encoding correctly (i.e. swapping & for %26). I ran into the issue in 2.2.0 where URL encoding was causing issues with the custom commands but saw that was just reverted. I think especially if the custom commands aren't going to be run through the `encodeURIComponent`, the maybe a browser source is worth making a custom action for. I've been doing a lot of OBS.ninja inside vmix and the amount of URL parameters I'm using really adds up.

**Comment by McHauge** [comment]
Hi, yes i reverted that to no encoding on custom commands, but it's not in the core yet. This was done simply because all 3-4 way i tried doing it, would break some action someone had setup in some way. Now it will be just like it was way before in 2.1.2.

But i don't think i understand quite what you are after, sorry 😅

Is BrowserNavigate  a shortcode (haven't looked) if it is, then sure i could add that for you with an encode URI Component around the Perameters for the link.

That would take 10min or so 😁

**Comment by jeffreylsoffer** [comment]
Yes BrowserNavigate is simply an API option for setting the URL of a browser source! I'd really appreciate it, thanks!

![image](https://user-images.githubusercontent.com/65000982/115434693-fc209880-a1d6-11eb-8c5f-4942d66ff251.png)

**Comment by McHauge** [comment]
Cool, I'll give it a look in a bit 👍

**Comment by McHauge** [comment]
Should be in there now, and seems to work for me at least, I also added the other browser actions :)

**Comment by jeffreylsoffer** [comment]
Thanks!! Now just gotta bug the bitfocus people to get it into the core...

**Comment by McHauge** [comment]
if you need it right now, then I can compile a build for you (mainly for windows) otherwise I think the core Devs is a bit hung up currently, but I would expect it to get merged over the weekend or in the start of next week

**Comment by jeffreylsoffer** [comment]
Nah! I'm totally fine. Thank you for doing this!!! Really appreciate it.

**Comment by McHauge** [comment]
as this is now part of the betas I'll close this
