### ISSUE TITLE
Destination Input Routing does not seem to work

### ISSUE THREAD

**Issue by jarihakkarainen** [bitfocus/companion-module-studiocoast-vmix#143]
**Describe the bug**
Destination Input Routing does not seem to work anymore.

**To Reproduce**
Steps to reproduce the behaviour:

1. vmix: Layer - Set Destination Input for Routable Multiview Layer --> $(vmix:mix_1_preview)
2. vmix: Layer - Set Destination Layer for Routable Multiview Layer --> for example 1
3. vmix: Layer - Set Source Input for Routable Multiview Layer --> for example 3

**Expected behaviour**
Input 3 to change to Layer 1 of the Input in Preview

**Screenshots**

**System (please complete the following information):**

- companion-2.2.0+3874-master-8f05f9f1
- vMix version 24.0.0.72
- 
**Additional context**

**Comment by thedist** [comment]
The major update does have some changes, now all text input fields parse instance variables now rather than just a random set, so `Set Destination Input for Routable Multiview Layer` will parse that instance variable when pressed.

So when you use that first action, you're setting the destination to whatever is in preview at that point in time the action is used. If you change what you're previewing in vMix, the destination will still be whatever it was when you used the action.

If your goal is to update whatever happens to be in preview at the time you use `Set Source Input for Routable Multiview Layer`, you can either add `vmix: Layer - Set Destination Input for Routable Multiview Layer --> $(vmix:mix_1_preview)` as an action right before it so that it'll update the destination when you try to set the input to the layer. 

Alternative you can use the `Layer - Set Input as Multiview Overlay Layer on active Preview input` action, which is always using the preview input of one of the mixes as the destination

**Comment by jarihakkarainen** [comment]
So let me just try to get this right. This is the way it used to work before:

1. I press a button which has the action `vmix: Layer - Set Destination Input for Routable Multiview Layer` with value of `$(vmix:mix_1_preview)` so that I can change the layout that is in preview.
2. Then I press a button to select which layer in the input that is in preview I want to change: `Set Source Input for Routable Multiview Layer,` let's say 1
3. Then I press another button to select which input I want to use as the input in the layer selected in step 2: `Set Destination Input for Routable Multiview Layer`, let's say it has the value of 3

When I do those steps, nothing happens. The third step used to change the input on the layer selected in step 2. What is the correct way of doing it now? I'm trying to get my head around this. :)

**Comment by thedist** [comment]
So a couple ways to check what's actually happening.

In a button, give it the text `$(vmix:layer_routing_input) ` and this should show the name of the currently selected destination input. On another button, give it the text `$(vmix:layer_routing_layer)`, this will show you what layer is selected (should be a number 1 to 10).

It's also possible to use the `Layers - Destination Input Indicator` and ` Layers - Destination Layer Indicator` feedback to see if the correct things are selected.

When they're showing that there's both a destination and layer set, try to use the `Set Source Input for Routable Multiview Layer` action and then go to the Log screen in Companion, enable displaying debug messages, and you should see something like `22.02.10 11:42:01 instance(vmix): Sending command: FUNCTION SetMultiViewOverlay Input=MV&Value=6,1` which in my case the destination was called `MV`, I had selected layer `6`, and I sent input `1` to that layer.

**Comment by jarihakkarainen** [comment]
If I give a button the text `$(vmix:layer_routing_input)` it flashes the correct layer for a fraction of a second and then goes blank if I do the action `Layer - Set Destination Input for Routable Multiview Layer`. On the other hand, `$(vmix:layer_routing_layer)` does not show anything at any point.

Debug Log detects the buttons I press but it doesn't show any command following the three actions (Set Destination Input, Layer, Source Input).

If it's any help, in the warning log every second generates maybe 25-30 lines of `instance(vmix): Error checking feedback: option.split is not a function`.

**Comment by thedist** [comment]
I'm not able to reproduce what you're experiencing, and the fact that it does briefly show the destination input then goes blank indicates for some reason something is setting it, then running that action again to unset it, as nothing other than that action should be updating the destination value.

Could you please export your Companion config and attach it, or upload it somewhere, so I can take a look at it as I can't tell what's going on without more info.

**Comment by lemanutitou** [comment]
Bonjour,
juste je suis novice mais j'ai le même probléme j'ai du tout réinstaller pour retrouver mes réglages.
Maintenant je n'ai peut etre pas tout installer. 
J'ai 8 streamdeck de connectés je n'ai jamais eu aucun probleme jusqu'a la version 2.

Désolé pour mon écriture je suis Français.


> Si je donne le texte à un bouton, `$(vmix:layer_routing_input)`il fait clignoter le bon calque pendant une fraction de seconde, puis devient vide si je fais l'action `Layer - Set Destination Input for Routable Multiview Layer`. Par contre, `$(vmix:layer_routing_layer)`ne montre rien à aucun moment.
> 
> Le journal de débogage détecte les boutons sur lesquels j'appuie mais il n'affiche aucune commande après les trois actions (Définir l'entrée de destination, le calque, l'entrée source).
> 
> Si cela peut vous aider, dans le journal des avertissements, chaque seconde génère peut-être 25 à 30 lignes de fichiers `instance(vmix): Error checking feedback: option.split is not a function`.

**Comment by thedist** [comment]
It looks like some errors may be due to the upgrade script not catching that change. If you're using layer routing actions/feedbacks created in previous builds of Companion, can you please delete them and create them again and see if you still have issues.

I have one more question about the actions. when you use `Layer - Set Destination Input for Routable Multiview Layer`, is whatever you're putting in the text field an actual input name, number, or GUID in vMIx? Because if it can't find an input that matches then it'll default to setting the destination layer to an empty string (so the Instance Variable wouldn't display anything). 

Other than that I'm still trying to see if I can reproduce the issue but it would help if I had your config so I can test exactly the same actions/options you are using.

**Comment by jarihakkarainen** [comment]
> Could you please export your Companion config and attach it, or upload it somewhere, so I can take a look at it as I can't tell what's going on without more info.

I have attached here the full Companion config. You can find the troublesome actions on page 3. The routing actions work their way from the top row towards bottom row starting from the button Preview.
[Full-config.zip](https://github.com/bitfocus/companion-module-studiocoast-vmix/files/8056289/Full-config.zip)

**Comment by thedist** [comment]
So what the issue was is that the upgrade script didn't correctly handle some of those actions/feedbacks, so the config had some numbers in places where the new version requires strings.

I've made changes to those actions/feedbacks in the config and they should work correctly now. For future reference, adding a new action/feedback should automatically default to the new way it handles, things, also, deleting the values in a text input and typing them in again will also resolve the issue with actions/feedback that were created prior to the update (and this should only be needed for options where there's only a number in there, anything with text should be fine)

[Full-config.zip](https://github.com/bitfocus/companion-module-studiocoast-vmix/files/8056431/Full-config.zip)

One thing to note though (which I didn't change as I wasn't sure if it was intended), your 2nd button on page 3, with the text `Preview`, sets the destination to input 13, if you want to set the destination to whatever is in preview at the time you press that button you would need to change it to `$(vmix:mix_1_preview)`.

I'm working on a fix to resolve this going forwards, but for the time being the solution is to just delete the actions/feedbacks and add them again, or to delete the values in any option that just is a number (for example if the option is `Call 1` then that's fine, but if the option is `1` then that would need to be cleared and typed in again.

**Comment by jarihakkarainen** [comment]
Thank you, I truly appreciate the time you take to look into this!

OK, I may have a hunch now, which you might want to take a look at. I imported your edited config and now the log shows correct commands being sent to vMix. At first, however, the commands didn't seem to do anything until I realized the name of the input in the command didn't have a space in it while in vMix the input has a space in its name. With inputs with no spaces in their name routing works just fine. So maybe the upgrade script is stripping out spaces?

While testing this I noticed there might be something wrong with the import script also. At first I did a full reset and imported your edited config in full and it resulted in every single button having actions that had `(undefined)` at the end and `Nothing to configure` next to them. When I imported individual pages, actions looked like they should.

**Comment by lemanutitou** [comment]
hello,
voici ma configuration page 28 PGRM.
Mais en faite c'est tout ma configuration qui ne fonctionne plus. Par contre avand la mise à jour tout était ok.

Apparement j'ai essayé de repartir de zero et votre mise à jour fonctionne parfaitement.
cela vient bien de chez moi et j'en suis sincerement désolé.

Je voudrais en profiter pour vous remercier du travail que vous faite et qui est absolument  super.
[11022022.companionconfig.zip](https://github.com/bitfocus/companion-module-studiocoast-vmix/files/8056559/11022022.companionconfig.zip)

**Comment by thedist** [comment]
@jarihakkarainen I'll look into the issue with spaces not being sent. The trouble is for some vMix functions spaces have to be handled in different ways but I'll see what's happening there.

As for things showing as undefined when you imported the full config, I believe that's because Companion needs to match up what actions are from which instance, and because I don't have the Atem, or X32 instances like you do all of those things show as undefined for me if I was to import them. Oddly, I had to import just the page too as importing the full config would crash Companion. I believe this is an issue on Companions side as when you import just a page you can select which instance matches up to which thing in the config, but this isn't an option for a full import for some reason.

@lemanutitou 
Salut, je peux regarder ta config demain et essayer de résoudre le problème. Je suis désolé pour toute perturbation que cette nouvelle mise à jour a pu causer.

Traduit avec Google

**Comment by lemanutitou** [comment]
Pas de probleme je ne vous en veux pas comment pourrais je vous en vouloir vous qui vous travaillé de longue dans ces développements
MERCI

**Comment by lemanutitou** [comment]
Hello,
Je viens de supprimer le module X32 enssuite j'ai re fait la mise à jour du module de la x32 j'ai rechargé toute ma configuration et tout refonctionne mes 8 streamdeck la x32 etc.
Le module vmix fonctionne proprement je suis super content

Merci merci merci
vous etes une belle personne merci de m'avoir aidé à comprendre

Cordialement

**Comment by lemanutitou** [comment]
Non finallement non Désolé je suis confu la fatigue surement
En fait en faisant la mise à jour je suis repasser a la verssion vmix d'avant 
Tout reste à revoir je me suis embaler trop vite

**Comment by lemanutitou** [comment]
Bonjour,
merci pour le fichier . Malheureusement rien y fait 
j’ai même recommencer avec 1 module unique vmix et ça plante grave mon CPU monte à 98%
il semblerait que ça vienne d'ailleurs.
J'ai tout effacé re installer companion sur 1 pc mais aussi sur mon MAC et si j'utilise la version module vMix avant la 2.0 tout fonctionne normalement mais dès que je passe à la version 2.0 ma page web se réinitialise tout le temps je ne peux absolument rien contrôler.

Heureusement que j'ai fais des sauvegardes je peux donc travaillé avec l'ancienne version.

Je n’arrive vraiment pas à comprendre.
Bien cordialement

**Comment by lemanutitou** [comment]
Pour votre info je suis prêt à vous communiquer un lien ZOOM par visio et vous partager mon écran.
J'ai un ami qui parle couramment votre langue donc ce serait trop bien.
En fait, peut-être que d'autres personnes que moi ont les mêmes problèmes et qui n'osent pas en parler si ça peut faire avancer le développement pourquoi pas.

A moins que je sois complètement nul et que j'ai fait les choses à l'envers c'est possible aussi.
Je ne suis pas un expert
Voila Jeff
je vais tout de même refaire des tests 
Cordialement

**Comment by thedist** [comment]
Essayez de reposer complètement votre configuration, de sorte qu'aucun bouton ne soit défini, puis essayez de mettre à niveau vers la dernière version en ajoutant vMix et voyez si vous avez toujours le problème.

Ma seule supposition pour le moment est que c'est parce que vous utilisez tellement de boutons sur la plupart des pages que Companion doit envoyer de nombreuses mises à jour de statut que la page Web ne peut tout simplement pas gérer. Si cela fonctionne bien avec un compagnon complètement vide, c'est probablement le cas et j'aurais besoin de développer un moyen de ralentir les mises à jour si le nombre de boutons utilisés dépasse une certaine quantité.

**Comment by lemanutitou** [comment]
Merci pour votre retour.
J'ai mis le strict minimum dans une configuration que j'ai refais j'ai tout supprimer et je n'ai garder que le module vMix.
Avant la mise à jour tout fonctionne apres plus rien.C'est à devenir fou.

Mais c'est toujours pareille le même probleme tout est super lent impossible de faire quoi que ce soit.

J'ai creer sur 1 nouveau projet et j'ai  ajouté les boutons  "Layers / MultiView - Set Destination Input for Routable Multiview Overlay Layer" quand j'appuie sur le bouton rien ne se passe.
J'ai remarqué que si je changeais le nom de l'entrée dans Vmix exemple pgrm1 sans espace ça fonctionne mais si je mets pgrm 1 avec un espace ça ne fonctionne plus.

Bon rien de grave je me contenterai de la version d'avant ne vous en faite pas en tout k merci bcp d'avoir pris le temps d'essayer de m'aider c'est sympas à vous merci encore.

Cordialement

**Comment by thedist** [comment]
@lemanutitou 
Il y a juste quelques correctifs qui peuvent aider, qui devraient à la fois aider à l'utilisation du processeur et aux espaces ne fonctionnant pas avec le routage d'entrée. J'attends toujours que ces modifications soient ajoutées aux versions bêta, mais cela devrait arriver dans les prochains jours.

Je ne sais pas si cela résoudra vos problèmes, mais j'espère que cela rendra la nouvelle version de Companion utilisable pour vous !

**Comment by lemanutitou** [comment]
@thedist 
Ouffff ça y est la version 2 fonctionne sans aucun problème.
J'ai tout remis à zéro avec les derniers correctifs et tout est rentré dans l'ordre en utilisant votre fichier
Merci encore pour tout
Et pardon à @jarihakkarainen pour mes nombreux messages.
