### ISSUE TITLE
Latest beta version does not recognize input names

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-studiocoast-vmix#147]
In the latest betas of Companion my vmix setup is broken for most of my inputs using name.  Some are still working and it appears that this issue may be connected with characters in the name.  For example:  CAM 1 FULL as an input name works but "CAM1 / PPT" does not.  Any help appreciated!  Thanks for all the work that goes into this!

**Comment by obcocav** [comment]
Fixed it!  Looks like the new shift feature delimiter value was interfering.  Changed the delimiter value on the connection setup page to "-" rather than "/" and all is well with that!

**Comment by thedist** [comment]
As you've found out, the text delimiter is used to split up text inputs so that everything prior to the delimiter is treated as the value for that text field when the button shift action isn't pressed, and everything after the delimiter is used as the value when the button shift is pressed.

This allows having multiple values on a single button, but does mean you need to make sure the delimiter is set to something that would never normally be used in the text input.
