### ISSUE TITLE
Latest beta causes "Select Title Preset" values to reset to 0

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-studiocoast-vmix#148]
After updated to the newest beta all my buttons to select title preset values reset to 0.  Works as expected when reset to the proper values.

**Comment by thedist** [comment]
Fixed in the latest commit, although this will not fix the issue for anyone who has already gone through the upgrade script with their currently loaded config so would need to either update the title preset values themselves, or import a config from before the major module update when Companion 2.2.0 releases.
