### ISSUE TITLE
Layer Tally Indicators overwrite png with background image

### ISSUE THREAD

**Issue by jaylaw64** [bitfocus/companion-module-studiocoast-vmix#150]
After placing a layer tally indicator on a button, if a button already has a .png. The tally indicator draws the background and text over the png so that it cannot be seen.

**Expected behaviour**
I would expect to see just the corner or border filled in with rest of the graphic present.

**Screenshots**

**System (please complete the following information):**

- Companion Version 2.2. release
- vMix version v24

Button without a tally layer
![Chalice no tally](https://user-images.githubusercontent.com/3117146/156335416-76a486b2-8245-43d4-a27e-68f64bacedda.png)

Button with a tally layer
![chalice tally](https://user-images.githubusercontent.com/3117146/156335441-3b57dbcf-18a1-40d6-8bef-c5b8fb5fd9bd.png)

**Comment by Julusian** [comment]
@thedist do you need anything from the companion side for this?
I havent tested this, but it looks like the `img64` property already accepts an `ARGB` buffer as well as `RGB`, so if you change how you are generating the buffer it should be able to draw properly.

Perhaps companion should change how it handles the img64 buffer, and should stack them when multiple feedbacks are used? so that two of this feedback on the same button will combine properly? That should be a simple change. The img64 property is only used by 3 modules, so risk is low and it wont be hard to do some breaking changes to it if needed. (As long as we do so before v3.0)

**Comment by thedist** [comment]
In the Companion Beta builds the layer Tally Indicators will now correctly be rendered over the top of any background image rather than replacing it.

**Comment by jaylaw64** [comment]
Awesome. Thank you!Sent from my iPhoneOn Mar 15, 2023, at 10:02 AM, Jeff Martin ***@***.***> wrote:﻿
In the Companion Beta builds the layer Tally Indicators will now correctly be rendered over the top of any background image rather than replacing it.
