### ISSUE TITLE
"Browser Navigate" issue

### ISSUE THREAD

**Issue by Tilltv** [bitfocus/companion-module-studiocoast-vmix#163]
I use the "Browser-Navigate" function to control a complex local web menu within vmix. 
For this I pass long urls with attached variables.
Unfortunately this doesn't work anymore. In the current version, only the first value is passed.

example url (sent with: browser navigate):
`localhost/presenter_c/session.php?session=settings_camera&step=2&goto=go_to_settingsmenue`

arrives in vmix:
`localhost/presenter_c/session.php?session=settings_camera`

missing:
`&step=2&goto=go_to_settingsmenue`

Everything from the first & sign is not transferred.

(No problems with version  2.2.0-c649d4bd-3529)

**Comment by thedist** [comment]
The issue is that vMix's TCP function handler uses `&` to separate parameters, so it thinks everything up to the ampersand is the url, and everything after is other params of the browserNavigate function.

We did at one point try to handle parsing of the URL to account for this but then other users complained that some stuff was being encoded that they didn't want encoded. So the way it's handled now is the module sends exactly the string you set, and if it needs encoding then that has to be done by you, such as replacing the `&` with `%26`.

If you change `localhost/presenter_c/session.php?session=settings_camera&step=2&goto=go_to_settingsmenue` to `localhost/presenter_c/session.php?session=settings_camera%26step=2%26goto=go_to_settingsmenue`.

We may review how we could improve handling of this in the future, such as a toggle box for if the URL should be encoded by the module or not, but for now you can encode the URL string yourself.

**Comment by Tilltv** [comment]
Ok, that makes sense to me. The feature for me may be a bug for others ;)
I didn't understand why it worked in older versions and shouldn't work now.
I would be happy if the function will be implemented in the future.

Now i will adjust the urls.
Thanks for the workaround!

**Comment by pdelbracio** [comment]
Hi.

@thedist 
This is indeed a BUG introuced at some point recently.

Hopefully it should be an easy fix.

After some testing I found that after upgrading to version 2.2.2 (2.2.2+4454-v2-2.2-be663609) what made this BrowserNavigate command to stop working is that the string for the URL gets cut after the first forward dash /

If you substitute your forward slashes for backward ones it solves the problem but it's not practical at all for complex URL that has lots of them as it needs to be done manually.


I tested multiple cases using forward and backward slashes and here's sample of the issue (I changed the URL to www.google.com for privacy reasons but I tested it with multiple ones:

Value=https:\\www.goggle.com\    WORKS OK
Value=https://www.goggle.com/    SENDS THE WRONG VALUE AS JUST "https:" AND DOES NOT WORK

You can see the difference when using forward or backward slashes this on this log extract (thankfully it now report the actual command sent on the log, which helped me track this down)

> 22.07.05 16:54:26 device(emulator): Button 99.2 released
> 22.07.05 16:54:26 instance(vmix): Command Response: FUNCTION OK Completed,
> 22.07.05 16:54:26 device(emulator): Button 99.2 pressed
> 22.07.05 16:54:26 instance(vmix): Sending command: FUNCTION BrowserNavigate Input=12&Value=https:\\www.google.com\
> 22.07.05 16:53:40 device(emulator): Button 99.2 released
> 22.07.05 16:53:40 instance(vmix): Command Response: FUNCTION OK Completed,
> 22.07.05 16:53:40 device(emulator): Button 99.2 pressed
> 22.07.05 16:53:40 instance(vmix): Sending command: FUNCTION BrowserNavigate Input=12&Value=https:

**Comment by Tilltv** [comment]
Hey, I have new problems with "browser navigate". In version 3.3.0 there is now the "URI encode" option. Unfortunately the links no longer work at all. no matter whether with or without encoding.

Neither works (with or without encoding):
`localhost/session.php?session=settings_camera&step=2&goto=go_to_settingsmenue
localhost/session.php?session=settings_camera%26step=2%26goto=go_to_settingsmenue`

**Comment by thedist** [comment]
This should no longer be an issue due to the previously added option to encode the URI on the action
