### ISSUE TITLE
No alternative to the deprecated show selected slide name

### ISSUE THREAD

**Issue by acidfrost** [bitfocus/companion-module-studiocoast-vmix#175]
Under feedback, there is the option to display the slide name from a slideshow or powerpoint input. It mentions being deprecated and to use a variable instead, but no variable exist in the variable list. The deprecated feature seems to still work. Any variable planned?

<DEPRECATED> Slides/List - Show Selected Slide/Index Name
Please use the available instance variables for text feedback

**Comment by thedist** [comment]
The current selected index of a list is the variable `input_X_selected`, and the name of the currently selected item is `input_X_selected_name`.

For example, if input 5 is a list named `listinput`, I could use the variables:
`$(vmix:input_5_selected`, `${vmix:input_listinput_selected_name)`, etc... and those would display the index of the current thing selected, and the second variable would be the name of that.

**Comment by acidfrost** [comment]
Hi,

These variable don't work. It's not a list put a powerpoint input, similar to a slide show. The deprecated feature works perfectly and displays the number of the slide currently live. Your 2 variables displays $NA:

![image](https://user-images.githubusercontent.com/68562713/187026905-a5c03982-a7bd-4f42-8160-5be5dbe03325.png)

![image](https://user-images.githubusercontent.com/68562713/187026914-3d7e3e80-6458-407a-b80a-41e245984b8d.png)

![image](https://user-images.githubusercontent.com/68562713/187026921-702153d3-1cd9-4bc5-afa9-d9b51af4b340.png)

**Comment by thedist** [comment]
The inputs name should be lowercase, eg `input_powerpoint_selected_name`

**Comment by acidfrost** [comment]
Yes lowercase or input number has the same $NA issue.

input_powerpoint_selected_name or input_5_selected_name doesn't work.

**Comment by thedist** [comment]
I'll look in to this, as that should work and did during my previous testing when we deprecated that feedback.

**Comment by acidfrost** [comment]
Hi! The latest release of Companion 3.0 still has the same issue. Is there an update? The deprecated feedback is gone from this version, so there is no alternative. Thank you

**Comment by thedist** [comment]
I've put off trying to properly implementing displaying of `PowerPoint` and `Photos` input types current item as I've been hoping that vMix would properly fix their API so that it would properly give details of the items.

For example with a `list` input, the API provides each and every item in the list (which is why it's the recommended way to handle a series of pictures or videos) which allows Companion to easily store all of the items and the currently selected as variables.

the `PowerPoint` and `Photos` input types on the other hand don't act as a list and so don't say how many items there are, what each item is.  If for some reason you MUST use these input types and can't use List I can add this to the list of feature requests for the next feature release, but it's not a high priority as vMix themselves don't fully support these input types and the List input is more commonly used.

**Comment by thedist** [comment]
I've added support in the latest update to the module that's currently in beta, and will soon be in Companion v3.3.0 stable, to add some more support for the currently selected item using the `input_X_selected` variable for photo and powerpoint input types. That being said unfortunately even after this time vMix's API itself still doesn't provide the full capabilities of what List input types to,
