### ISSUE TITLE
Only 15 mixes controllable, but 16 available

### ISSUE THREAD

**Issue by robertskiba** [bitfocus/companion-module-studiocoast-vmix#182]
**Describe the bug**
Only the first 15 mixes can be controlled over the module, not 16! 

**To Reproduce**
Just add Mix2 up to Mix16 in vMix26 beta. You can only control 15 mixes. 

**Expected behaviour**
vMix26 has 16 mixes available. Mix1 is always the PGM plus a maximum of 15 additional mix inputs. So you should be able to select mix1 up to mix16 in all commands. 

**System (please complete the following information):**

- Companion Version 2.4.1
- vMix version 26.0.0.20

**Comment by thedist** [comment]
Already fixed in the most recent commit, it's just not merged into Companion yet.

Also please keep in mind that vMix 26 is in beta, and the vMix devs can and have made changes in previous versions right up until a few days before they release so don't expect full compatibility until they lock in their feature set.
