### ISSUE TITLE
Linear volume feedbacks do barely work at the moment

### ISSUE THREAD

**Issue by robertskiba** [bitfocus/companion-module-studiocoast-vmix#185]
**Describe the bug**
While testing to use the encoders of SD+ with vMix26, I tried a workaround to change the audio levels of vMix using the internal function "Modify Variable Value with Math Operation", I took the corresponding linear variable value, added or subtracted a value and wrote it into a custom variable. Then I sent the variable value with a custom command to vMix. 

While doing that, I found out that those linear variables seem to have a problem at least with vMix26 (maybe even already with the current v25, couldn't test it). the variables don't give a linear feedback from 0 to 100. It only works from 60 to 100. The value never is lower than 32. I don't know if it's an error from vMix or the companion module. 

**To Reproduce**
Steps to reproduce the behaviour:

Just put all those linear audio variables on some buttons, play around with the volume controls of master, busses and inputs and you will see yourself. 

**Expected behaviour**
the variable feedbacks should be between 0 and 100 to be able to read a linear information about the current volume levels. 

**System (please complete the following information):**

- Companion Version 2.41
- vMix version v26.0.0.23

**Comment by thedist** [comment]
It's a bug with the Companion module because we round the volume for all volume types. eg linear 31 is volume 0.923521, and linear 32 is volume 1.048576, so rounding while suitable for other volume types is perhaps not useful for linear. No one I know uses linear volume as it's not particularly useful or representative of actual volume level so this hasn't been previously caught. I'll add it to the Companion 3 bug fixes.

**Comment by thedist** [comment]
Fixed in 59ef2857b28c5a5185c16b962dc056fc98da6b47
