### ISSUE TITLE
vmix: Layers - Destination Input Indicator : does not work with Preview or Program

### ISSUE THREAD

**Issue by PLRNA** [bitfocus/companion-module-studiocoast-vmix#186]
**Describe the bug**
When creating a feedback for a button, feedback type is vmix: Layers - Destination Input Indicator,
when cannot have an indicator when working with preview or program as input of the feedback. Also tried with 0 and -1

Input 0 and -1 works with other vmix companion functions, such as : 
vmix: Layer - Set Destination Input for Routable Multiview Layer

- Companion Version 2.4.0
- vMix versionV25 0.0.34

**Comment by thedist** [comment]
This is more of a feature request than a bug. Most other functions support 0 or -1 because they are vMix functions, where as this action is entirely a Companion thing.

Right now you can just use an instance variable that points to the preview or program input, but I'll add support for 0 and -1 to the list of feature requests for after the Companion v3 update is completed.
