### ISSUE TITLE
Getting GUID by input number

### ISSUE THREAD

**Issue by Hubaxis7** [bitfocus/companion-module-studiocoast-vmix#202]
**Describe the feature**
Please add to the module interface a button for getting GUID by entry number.

**Usecases**
In the "Input" field I would like to get GUID by button (get GUID) from vMix program. It would be very convenient and would save a lot of time when adding/removing new action inputs. The vMix program must be running at the moment.

![input get GUID 2](https://user-images.githubusercontent.com/22938004/231779594-a6162767-1f9a-4bde-aa7a-c616f98fc68a.png)

![input get GUID 1](https://user-images.githubusercontent.com/22938004/231778063-80373646-dfb0-4f92-9fc1-9b24d3782064.png)

**Comment by thedist** [comment]
Modules themselves can not add buttons like that to the UI, that would need to be requested to Companion themselves.

Additionally, GUIDs are represented in both the Variables tab, and through the Companion HTTP endpoint `/instance/INSTANCE NAME/data`.

It should be noted though that not many use GUIDs due to the associated issues with them, for example if a new input is create and an old one removed you will need to update ALL actions/feedbacks/triggers/text using that GUID. While we support using GUID, it's much more common to use input name and stick to a proper naming scheme for your production.
