### ISSUE TITLE
Module crashing to "Unknown Stopped" state after some period of time. 

### ISSUE THREAD

**Issue by DanielWilliamsMSC** [bitfocus/companion-module-studiocoast-vmix#214]
**Describe the bug**
Module crashing to "Unknown Stopped" state after some period of time. 

**To Reproduce**
Leave vMix and companion idle for >4 hrs (at least, unsure on timeframe)

**Expected behaviour**
Stays connected

**Screenshots**
![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/125619541/aaa2ecf7-5375-4c29-b157-89ace1cf5b14)

**System (please complete the following information):**

- Companion Version 3.0.0-5990
- vMix version latest

**Additional context**
Seems to be when leaving unattended, vmix and companion run on the same machine. Other companion modules are staying connected. vMix is still running and works correctly. 
Disabling and re-enabling the vMix module immediately reconnects.

Have tried creating a trigger like this to fix, however whatever is happening, doesn't fire the trigger. 

![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/125619541/fb50bda7-7add-4d19-baf3-20a4d5f5ee9a)

**Comment by thedist** [comment]
If vMix is idle then it could simply be the TCP connections are being dropped for inactivity by the system.

Please try the latest Beta build as we already have a change in place to help alleviate issues from systems/networks from dropping inactive connections.

**Comment by Julusian** [comment]
`Stopped` looks like Companion stopped the module for some reason and didnt restart it. I don't know why it would be doing that though

**Comment by JAYovr** [comment]
this still happens on the latest companion build

**Comment by thedist** [comment]
If you're still having issues with the Beta version, check your log for the instance (the `>_` icon on the Connections tab) and see if anything shows there.

Also, while running vMix go to its API page of the web interface, `http://localhost:8088/api` (replacing localhost with the IP of where you're running vMix, and 8088 with the Web Interface port) and then copy/paste the data into a text file so that I can try see if I can replicate the issue you're experiencing as right now I can't replicate it.

**Comment by thedist** [comment]
No further info so closing for now.
