### ISSUE TITLE
vMix Video timer 

### ISSUE THREAD

**Issue by LauHaslund** [bitfocus/companion-module-studiocoast-vmix#233]
The video timer feedback function doesn't show the remaining time of a vMix video in the new version of companion.
It does change textcolor when the remaining time is less than 10 sec, but no timecode as it was in version 2.4.2.

Companion version 3.1.1
vMix 26.0.0.38

Cheers
Lau Haslund 

Is it a bug or am I missing something?

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System (please complete the following information):**

- Companion Version [e.g. 2.2.0 (70d5207-2717)]
- vMix version [e.g. v23]

**Additional context**

**Comment by thedist** [comment]
It's an intentional change for feedbacks in v3 to not change text on a button.

Instead you can use the appropriate instance variable, eg `$(vmix:input_X_remaining)`, `$(vmix:input_X_remaining_ss)`, `$(vmix:input_X_remaining_ss.ms)`, `$(vmix:input_X_remaining_mm:ss)`, or `$(vmix:input_X_remaining_mm:ss.ms)`. Where `X` is the inputs Name, Number, or GUID. This means that not only can you display the time remaining on a button but you can also use it as an input to another action/feedback.
