### ISSUE TITLE
Specfic feedback issue with preview and layers

### ISSUE THREAD

**Issue by stevespaw** [bitfocus/companion-module-studiocoast-vmix#242]
**Describe the bug**
If a "mix2" is in a layer that is currently "on-air" , the feedback for that mix2 gives a program tally for a mix2 that is native on Mix1 (the main program) This is fine.

If I select that Mix2 alone in preview to go full screen - nothing I do will show PREVIEW feedback for that fullscreen mix2 sitting in Preview for the main mix (Mix1).

**To Reproduce**

1. put mix2 on a layer box with a background on air
2. make a PROGRAM button for plain mix2 setting program and preview different colors
3. make a PREVIEW button for plain mix2 setting program and preview different colors
4. Put mix 2 in preview

**Expected behavior**
I should get proper preview feedback.
But I do not, preview for that solo mix2 will not register if mix2 in a layer "on air"

I have tried with all mixes, this may be an issue for any input involved in layers, I am working on this particular issue at the moment.

**System (please complete the following information):**

- Companion Version 3.2.0  release
- vMix version [v27]

**Additional context**

**Comment by thedist** [comment]
I don't quite understand the issue you're having.

If Mix 2 Program is in Mix 1 Preview, it'll show up as `Tally - Preview state` feedback.
If Mix 2 Program is a layer in Input 5, and input 5 is in Mix 1 Preview it'll show up as `Tally - Preview state` with whatever you have the `Layer Tally Indicator` set as, because Mix 2 Program isn't in Mix 1 Preview, it's just a layer in something that is so it's the `Layer Tally indicator` option that is displayed.

**Comment by stevespaw** [comment]
I thought this might be hard to communicate, I can see  `Tally - Preview state` going from false to true, but the feedback color does not change. I will try to make a video of a simple setup with a few inputs to demo.

**Comment by thedist** [comment]
Closing this issue for now as I don't seem to see any issue unless I'm misunderstanding the problem. If it can be explained what the specific issue is I'll reopen.
