### ISSUE TITLE
Layer feedback

### ISSUE THREAD

**Issue by RealParSec** [bitfocus/companion-module-studiocoast-vmix#245]
**Describe the feature**
Feedback if layer **x** on input **y** is on or off.

**Is this version dependent (vMix v24.)?**
26

**If documentation is required to implement, do you know where to find it?**
I don't know where to look for.

**Usecases**
Having multiple layers where you can toogle them and see which layer is on.

I made a switch for all 10 layers but there is no feedback.
![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/18197204/30f5bee9-79dd-4d65-88ae-b0ca8b48976f)

**Comment by thedist** [comment]
vMix's API provides no data as to if an layer is enabled or disabled, so it's impossible for Companion to represent that.

One workaround that can be done is instead of enabling/disabling a layer, you instead change the layer from the input you want, to a transparent input. This way you can use feedback to check which input is set to a layer and if it's the one you want visible then the feedback can indicate as such.

Unfortunately there's no simpler way to do this because vMix doesn't provide the data Companion needs, this is something we've requested but some of the requests for more API data go back years with no sign of them adding what is needed.
