### ISSUE TITLE
QUESTION: "Tally" for input layer on/off?

### ISSUE THREAD

**Issue by JaaHann** [bitfocus/companion-module-studiocoast-vmix#249]
Is there any feedback to get the visibility state of an input layer?

I use the "Layer - Toggle/On/Off Multiview Layer on Input" action a lot and would like to get the current visibility state of an input layer as feedback.

**Comment by thedist** [comment]
vMix's API does not provide any data as to if a layer is enabled or disabled, so unfortunately Companion has no way to give feedback directly as we can see what input is set to a layer but not if that layer is enabled/disabled.

In another issue, #245, I explained one workaround to get feedback that uses changing a layer to a transparent input to disable it, as then there can be feedback on if the layer is set to transparent or something else. So that thread may be an option for you.
