### ISSUE TITLE
Audio - Bus mute Feedback distinct selections...

### ISSUE THREAD

**Issue by clafarge** [bitfocus/companion-module-studiocoast-vmix#259]
**Describe the feature**
Currently, Feedback configuration for Audio - Bus mute requires selection of both "Foreground Color" and "Background Color". 
![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/6752214/c7b6919b-e7fa-4420-812c-6109ed1727cc)

Many feedback options exist that allow for selection of the affected decorations to apply.
![image](https://github.com/bitfocus/companion-module-studiocoast-vmix/assets/6752214/e28ea7e2-6d57-43f1-b735-83a3d4046b30)

It would be helpful to be able to choose an aspect of the feedback to be effected instead of forcing 2 and only 2 chrematistics. Alternatively, allowing for the selection of [transparent] might allow for stacking feedback channels.

**Usecases**
Allowing for the selection of different feedback methods makes possible monitoring of the same setting for multiple connections, such as vMix A Bus A is muted (background dark red) and vMix B Bus A is muted (text bright red).

**Comment by thedist** [comment]
The main reason why most feedbacks in the vMix module don't support selecting specific styles is because that's only available on `boolean` feedbacks, where as most the feedbacks are set to `advanced` which allows for more complex things but the downside is that it doesn't offer the style selector or use in triggers.

One of the things I am working on for the next big update to the module though is reviewing all actions/feedbacks and allowing variables to be used in many more places, and for feedbacks such as this where a `boolean` feedback could be possible I'll be looking to make that change too.

**Comment by thedist** [comment]
The latest Beta version has significantly more `boolean` feedback types, so will allow for selecting the style options in the feedback as well as allowing for use in triggers.

This is currently in the Companion Beta versions, and will be in the soon to be released Companion v3.3.0 stable.
