### ISSUE TITLE
How does one install an updated module?

### ISSUE THREAD

**Issue by knbpixels2** [bitfocus/companion-module-studiocoast-vmix#266]
I tried replacing the files in my current Companion vMix module folder with the latest files from the updated module, and the connection became disabled when I relaunched it.   I'm sure I'm doing something wrong, how does one install an updated module?

**Comment by thedist** [comment]
Just download the latest version of Companion and install it. The Stable version, v3.3.0 of Companion was released just yesterday and includes the latest version of the vMix module. There's no need to download individual modules.

When I make changes to the vMix module they'll be added to the Beta builds of Companion so that can be installed to get brand new changes between Stable releases, but right now the latest vMix is in Stable.

**Comment by knbpixels2** [comment]
Very good, thanks!
