### ISSUE TITLE
Feedback vmix: Audio - Input mute (sometimes) broken from 3.5.4 to 3.6

### ISSUE THREAD

**Issue by richardgatarski** [bitfocus/companion-module-studiocoast-vmix#267]
This feedback stopped working as expected after I upgraded to Companion 3.3.0.
In 3.5.4 the feedback was configured for "live" and for "muted" color. I chose red for live and black for muted.
In 3.6 the feedback is configured only for muted, which is black (I assume the button's default BG is for live).

My choice of live for red is ignored (not propagated to the default BG) configuration. Perhaps this could not be fixed automatically when importing from a previous version of the vMix module. But, a warning, and how to fix (change the default BG for affected buttons) would come in handy. Not sure if similar changes have been made for other feedbacks (at least I cant find any in the patch notes).

Companion
- companion-win64-3.2.2+6688-stable-7417d2a0
- companion-win64-3.3.0+6991-stable-b27baf94
- vMix version  v27.0.0.75

**Comment by thedist** [comment]
Many feedbacks were changed from Advanced to Boolean, Input Mute being one of them. Unfortunately because of the nature of that feedback where it had mistakenly had 2 background options, only 1 background option could possibly be used in the upgrade script and so in discussion with those who assisted with the Beta testing as the feedback is active when an input is muted the upgrade script copied the colour the from the muted background state.

If users need to have it the other way around then either the default button colour can be styled how you like when the input is not muted, or because it's a boolean feedback now you can just toggle the 'inverse' option and it'll be active when not muted as opposed to active when muted.

I'll add more of a warning for changes like this in the future, as I had not considered edge cases who had configured the styling in non-standard ways.

> Not sure if similar changes have been made for other feedbacks (at least I cant find any in the patch notes).

The patch notes do include that feedbacks have changed and have individual styling, we went from something like 2 boolean feedbacks to I believe 27
`Significantly more Boolean type feedbacks where applicable (allow individual styling, and use in Triggers)`

**Comment by richardgatarski** [comment]
Thanks for the quick response and elaborate explanation! I did see that patch note. But, being a cheap user with no insights in coding Companion, I simply did not understand what "Significantly more Boolean type..." meant. I sort of took it as something had been added rather than changed ;)

In my case I went for the 'inverse' fix which worked fine. I then had to check all my vMix feedbacks as I did not know if any of them was among the 27 booleans.

Best of all, I can now use variables for addressing Mix Inputs! Thanks man!!

**Comment by thedist** [comment]
If it helps with checking feedbacks for what may have changed, the ones that were 'boolean' before Companion v3.3.0 were just `General - Dynamic Input or Value` and `General - Input State`.

In Companion v3.3.0 the following were changed to that type too:
```
vMix - Status
Audio - Bus mute
Audio - Bus solo
Audio - Input mute
Audio - Input Audio Auto
Audio - Input solo
Audio - Input Bus Routing
Audio - Bus Volume
Audio - Input Volume
Media - Input Loop
Replay - Recording/Live
Replay - Events Tab
Replay - Camera Live
Replay - Selected Channel
Video Call - Audio Source
Video Call - Video Source
Slides/List - Change style based on an inputs Selected Index
Layers - Destination Input Indicator
Layers - Destination Layer Indicator
Layers - check if input is on destination Layer of destination input
Layers - check if X input is on Layer on Y input
Util - Mix Selected
Util - Bus Selected
Util - Button Shift state
```

I don't believe any of those had the same sort of multiple background options that Audio Mute did, so those should more seamlessly update.

In the future I'll be sure to include more in-depth change logs like this so it should be easier for people to check if any of their setup might have changed.
