### ISSUE TITLE
Feedback Tallies ability to change PNG graphic

### ISSUE THREAD

**Issue by sackboydad** [bitfocus/companion-module-studiocoast-vmix#280]
**Describe the feature**
Would it be possible to add a feature in the feedback section to allow tallies to change the PNG graphic in addition to the text color and bkgd color of a button?

The ATEM module lets you change almost everything about a button's look depending on whether it's PGM or PVW tally is active.  I'd also request this for overlay tallies as well.   

<img width="714" alt="Screenshot 2024-08-28 at 09 40 51" src="https://github.com/user-attachments/assets/ae14a564-3ea2-4519-bf91-bf684280b7c1">

thank you for your consideration

**Comment by thedist** [comment]
Being able to set any type of style is only applicable to Boolean feedbacks, it's not available to Advanced feedbacks such as the vMix tally feedback because we more options than just on or off (eg, the program tally can differentiate between an input in program, and an input that's in a layer of some other input that's in program).

Because of this, it's not possible to add that capability to that feedback. Instead if you just wanted a simple boolean value, you could use variables like `$(vmix:input_X_mix_Y_tally_program)` to see if input X is in mix Y program, and then use that variable in `internal: Variable: Check value` which is a Boolean feedback so will let you change the PNG and other styling options, but doesn't differentiate between an input being the mix preview/program, or just being a layer in an input that is the mix preview/program.
