### ISSUE TITLE
Add input_x_selected_name Support for Photos Input (PR #285)

### ISSUE THREAD

**Issue by Haavard15** [bitfocus/companion-module-studiocoast-vmix#286]
**Describe the feature**
I am proposing to add support for input_x_selected_name to the Photos input type, as seen in [commit 571688b](https://github.com/bitfocus/companion-module-studiocoast-vmix/pull/285/commits/571688baee9f31629c8995cc304c10d1dc11f3e3). This change allows users to retrieve the selected photo’s name by:

- Including the Photos input type in the selected index tracking.
- Adding a variable to capture the selected photo's name (input_x_selected_name).

**Is this version dependent (vMix v24.)?**
No

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
Having the name visible in the button so you can confirm the content before you press it

**Comment by thedist** [comment]
This is something we can add in to the 3.7.0 update, but what I would like for you to change with your PR is if you're going to add support for `input_x_selected_name `, to also support it in `dynamic_input_x_selected_name `, so that it matches how variables are handled for list inputs also giving variables for dynamic inputs.
