### ISSUE TITLE
Additional button features in Feedback

### ISSUE THREAD

**Issue by sackboydad** [bitfocus/companion-module-studiocoast-vmix#287]
**Describe the feature**
Please add additional button attributes to change during feedback.  in the ATEM companion module on a Tally state feedback, you can change not only the button background and text, but also the PNG graphic, font size, text alignment, PNG alignment, etc.  This allows using PNG graphics to enhance the look of the buttons (example attached).  

**Is this version dependent (vMix v24.)?**
No

**If documentation is required to implement, do you know where to find it?**
I don't believe so.

**Usecases**
To be able to use graphics to enhance the look of buttons.  Example attached has the buttons looking like actual switcher buttons.  The PNG graphic can change based on tally.  The graphic package I have from ATEM has 3 buttons for each .... clear no tally, red tally and green pvw tally.  The text inside the button is button text.  
<img width="914" alt="Screenshot 2024-10-07 at 08 47 06" src="https://github.com/user-attachments/assets/885b3b53-57d6-4328-959e-9ca4373a3d46">
<img width="275" alt="Screenshot 2024-10-07 at 08 47 36" src="https://github.com/user-attachments/assets/b1519db5-84ec-4b0d-83cb-919b4bf055f0">

Thank you for your consideration!   I'd really love to see this feature.... let me know what kind of tip would be warranted :-)

**Comment by thedist** [comment]
The reason why the ATEM feedback can do those additional style properties is because it is a BOOLEAN feedback, meaning it only has 2 states, on or off. Whereas the vMix feedback utilizes an ADVANCED feedback, meaning it has more than one state. (eg it can indicate if an input is not in program, in program, or in program as a layer of some other input).

ADVANCED feedbacks can't use the customized styling of BOOLEAN feedbacks, because there's no way to differentiate which styling should be used for the multiple different possibilities.

What you can instead do, is use the `Variable: Check value` feedback, as that's a BOOLEAN feedback, and then have it check a variable such as mix_1_program_name, or whichever variable you wish to check, and if it matches then the feedback will set the styling you choose. Or if you want to check if an input is in program as a layer, you could use `input_X_mix_Y_tally_program` (where X is the inputs name, number, or guid, and Y is the mix number).

So you can already achieve what you're interested in doing using internal feedbacks, just keep in mind that simple BOOLEAN feedbacks aren't going to differentiate between an input being sent to program, and an input being in a layer of an input sent to program.

**Comment by sackboydad** [comment]
Thanks, Jeff!

On Oct 7, 2024, at 09:17, Jeff Martin ***@***.***> wrote:



The reason why the ATEM feedback can do those additional style properties is because it is a BOOLEAN feedback, meaning it only has 2 states, on or off. Whereas the vMix feedback utilizes an ADVANCED feedback, meaning it has more than one state. (eg it can indicate if an input is not in program, in program, or in program as a layer of some other input).

ADVANCED feedbacks can't use the customized styling of BOOLEAN feedbacks, because there's no way to differentiate which styling should be used for the multiple different possibilities.

What you can instead do, is use the Variable: Check value feedback, as that's a BOOLEAN feedback, and then have it check a variable such as mix_1_program_name, or whichever variable you wish to check, and if it matches then the feedback will set the styling you choose. Or if you want to check if an input is in program as a layer, you could use input_X_mix_Y_tally_program (where X is the inputs name, number, or guid, and Y is the mix number).

So you can already achieve what you're interested in doing using internal feedbacks, just keep in mind that simple BOOLEAN feedbacks aren't going to differentiate between an input being sent to program, and an input being in a layer of an input sent to program.
