### ISSUE TITLE
titletext variable of empty text layer returns `undefined` as string not ``

### ISSUE THREAD

**Issue by semenovnick** [bitfocus/companion-module-studiocoast-vmix#295]
**Describe the bug**
I don't know if it is a bug. But some of my feedbacks stopped working. In previous versions of Companion for example on 3.3.1 and earlier variable of titletext if corresponding text layer is empty (no symbols) returns ``. Now it returns `undefined` which is in boolean feedback returns true only with

`$(vmix:input_x_layer_4_titletext)=='undefined'`

Other operations: 

`strlen($(vmix:input_x_layer_4_titletext)) => 9`

`bool($(vmix:input_x_layer_4_titletext))=> true`

**To Reproduce**
Add title input into vmix
Make text layer empty

**Expected behaviour**
When `$(vmix:input_x_layer_4_titletext)==''` returns `true` it was better

**System (please complete the following information):**

- Companion Version [3.4.3]
- vMix version [26.0.0.45]

**Comment by thedist** [comment]
This appears to be a bug due to a previous patch that went out to try to fix issues where if a title contained certain keywords, such as 'true', 'false', 'null', etc... it would cause the XML parser to parse them as those types rather than strings, which has had the unintended consequences of turning empty titles into 'undefined' because in the vMix XML an empty title is technically undefined.

I'll push out a patch today so that empty titles should once again be just an empty string rather than undefined.

**Comment by thedist** [comment]
This should be resolved in the latest Betas, and whenever the next Stable release will be.
