### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by frankleggett** [bitfocus/companion-module-studiocoast-vmix#34]
As of today VMix Feedback isn't working.
I have tried 
Input on Program
Input on Preview
Overlay Status

I am now using Companion 2.1 but it didn't work with 2.0 Beta
I have cleared my pages and put in fresh buttons and the Feedback doesn't work.

**Comment by frankleggett** [comment]
I have noticed that feedback works if I reduce the number of inputs below 25, I have a lot of captions as inputs so I need a lot of inputs.

**Comment by McHauge** [comment]
@frankleggett hi, yes there is a bug with feedbacks, if you have an empty list they will freeze, but I posted a fix for it yesterday, should be merged into the beta builds in a few day, I can post a link the you can try it out now.

But if you have a list item that is empty, just place a place placeholder item and it should work again.

Hope it's okay that I close the issue as it has been fixed in this version of the module.

**Comment by McHauge** [comment]
@frankleggett  you can download a compiled version with the fix for windows at this link:
https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g

**Comment by frankleggett** [comment]
Thanks Andreas, really impressed with fast feedback. I’m new to companion do I need to reload the module or does it update automatically?

**Comment by McHauge** [comment]
@frankleggett if you use the build I made, then yes it will be updated automatically, but if you go on the webpage and download the newest beta builds there, then it won't be for the moment being. I'm currently waiting for someone with the power to update it to come home from vacation. but when they do, it will be updated in the main build.
