### ISSUE TITLE
[BUG] vMix Feedback Mix 2-4 does not work

### ISSUE THREAD

**Issue by videochris** [bitfocus/companion-module-studiocoast-vmix#47]
vMix Feedback Mix 2-4 does not work
Only Mix 1 gives a feedback.
![vMix_Feedback_01](https://user-images.githubusercontent.com/59860887/97461170-c8f30000-193d-11eb-9b20-d877a08f38c1.jpg)

**Comment by thedist** [comment]
While the vMix API doesn't provide the data we would need to have feedback as to output routing, one option that may be available to you if you have the 4k or Pro version of vMix is that you can add Mix 2, 3, and 4, to your inputs as McHauge described, and then you can assign those to outputs 2, 3 and 4 respectively.

Then to change what is being fed to an output you just change what is in program for that mix rather than change the output, this has the advantage you'll now be able to have feedback as to what's going to each output as all 4 mixes do provide that capability. The downside to this that it requires the 4k or Pro version, plus you can only output what is in your list of inputs (so if you wanted to output a multiview, you would need to make an input yourself for that).
