### ISSUE TITLE
Use GUID as input reference

### ISSUE THREAD

**Issue by ruudboon** [bitfocus/companion-module-studiocoast-vmix#49]
All input are now now number based. Would it be possible to make this a dropdown with names and reference to the Guid (https://www.vmix.com/help23/index.htm?DeveloperAPI.html, see input section)?
When moving inputs around in vMix it currently breaks the link with companion.

**Comment by McHauge** [comment]
currently, you can use both the input number and the input name in all actions and feedback. talked a bit about the use of GUID in issue nr #30 but were open for discussing it.

**Comment by ruudboon** [comment]
@McHauge ah Missed #30, sorry.
Would a dropdown with the input be the preferred solution?

**Comment by McHauge** [comment]
yes and no, is my opinion. my problem with GUID is mainly the fact that it locks you to one setup. eg if I create a setup one day and a new one for the second I can't easily reuse the same companion, as I could if I made it work with generic names, like renaming all inputs to something like, Cam 1-8, Call 1-8, graphic 1-4 and so on, with guid your locked so if you close an input on accident you have to redo all buttons again with the new input. with the use of Input names, you can just rename your input to match the one you closed and all the actions will work again. the only input type where you can't use the name but need to use the number is a list input, since it changes it's name based on what it's showing, also on calls they will change unless, if you rename it manually then it keeps it's name

**Comment by McHauge** [comment]
but there might be a way to make the module togglable between GUID and number/name in the config, but I'm not sure if that would help or confuse the module.

**Comment by ruudboon** [comment]
Excellent point. I will give it some more thinking time. My main issue is the number of stills and movies you often get last minute. I want to easily patch them. Renaming or using numbers is time consuming and you easily make mistakes

**Comment by McHauge** [comment]
this is true and i see the point, and I also end in the same dilemma sometimes, and have begun to create still 1-8 and vid 1-8, as dymmy color bars that are re-named when I set up the show before the event, then on the day I can quickly replace them with the correct files and they still keep's their names. 

One middle of the road, could be a dropdown with input names, but still based on their name, not the number/guid. but if you come up with a solution/idea please let us know. it's a bit simpler on hardware with a locked number of inputs :)

**Comment by ruudboon** [comment]
Need to think about it a bit, I understand all the angles. I got the feeling there is a solution that can work for every situation just need to come up with something the works in the UI as well.

**Comment by thedist** [comment]
The trouble with using GUID's is not an issue from a technical standpoint, but with usability.

If actions/feedback references GUID then changing the name of an input would let the buttons still function, but then again if you need to replace the input, say for example a video file to be played back got updated, then suddenly that's a new GUID even if named the same and so that would mean every action/feedback would be updated.

If it's not clear to the user that GUIDs are being used and not names, that could also cause confusion to those trying to configure Companion when they may delete an input and put something new in its place and it's not working in Companion because it's a different GUID (which wouldn't be clearly visible to the end user).

My thoughts for a solution would be is if there could be an additional help page, one that shows a mapping of input Index, Name, and GUID. Then a user could copy/paste the GUID for the input into their buttons. A dropdown box for inputs wouldn't be appropriate as I know many users who build a show before they have all their inputs sorted, for example you may want a button to go to colour bars but if it's not currently in vMix then it wouldn't be in a dropdown, but if the user knows they always name that input `BARS` then it doesn't matter if it's currently an input or not.

There could be a config option to switch between a text input for input Index, Name, or GUID (and at the very least adding support to check for input by GUID if the user were to paste one into the text box would be simple, and without issue, to add) and switching to a dropdown, but then that would limit mixing and matching where you may want to use names for some inputs, and GUID's from a dropdown in another.

**Comment by McHauge** [comment]
just tested, and currently GUID is supported in actions, just coppy/paste into the input field, i'll ad a checkbox on feedbacks that can be ticked on for using GUID as a input in those

**Comment by ruudboon** [comment]
My main request here was creating the dropdown with clips so you don't have to copy paste. When doing this I think it makes sense to use the guid so you're sure you have that clip. If you change the name the select menu will be updated. If you delete the clip it will show the default option.

**Comment by McHauge** [comment]
would it make sense to post them as variables under the instance, so you can copy-paste from that page? I feel like that might get crammed but with the scheduler coming it might not be that bad to have anyway.

**Comment by ruudboon** [comment]
Not sure what you mean with the variables. I was thinking something like this:
<img width="547" alt="Screenshot 2020-11-10 at 23 45 18" src="https://user-images.githubusercontent.com/7444246/98742550-ecdb2a80-23ae-11eb-95d0-81c159fa84b5.png">
So default option is use textfield and you use the textfield input. Or you can choose a clip in the dropdown that holds a lists of all inputs.

**Comment by McHauge** [comment]
I think that would be dangerous but might work, the thing again if you change the input type, or file or something that triggers a new GUID, but you did not close it and open it again. the user would think that it would still be locked to that input even though it's a completely different one.

**Comment by ruudboon** [comment]
If the selected GUID isn't in the dropdown list we can switch back to the Use textfield or add an extra option with Input missing.

**Comment by McHauge** [comment]
Currently it's just the text field that accepts input nr, name and GUID, it then self detects and send the apropiet. I removed the check box again as it wasn't necessary after all.

**Comment by McHauge** [comment]
I'm gonna close this, for now, feel free to open it up again if something comes up, but currently, GUID's are supported as inputs in actions and feedbacks.
