### ISSUE TITLE
Polling not receiving data

### ISSUE THREAD

**Issue by robsumm** [bitfocus/companion-module-studiocoast-vmix#60]
Having built a new companion Pi and copied the setup over I am not receiving the polling data on the new Pi which has the latest version of the instance which uses TCP polling. on the working system I have 2.1.1(4e15977-2611) on the new Pi it is 2.1.1(8b50f72-2662)
The connection is working in as far as I can push the buttons and it triggers vmix but I am only receiving data up to Vmix:input_6_name (I have 26 inputs in this current Preset)
On the vmix machine I have added port 8099 to incoming and outgoing in the firewall and also turned off the firewall but neither makes any difference.

**Comment by thedist** [comment]
I'm currently investigating this. It's not going to be a firewall issue or anything like that because the TCP connection used for feedback is the same one used for functions, and as they work it indicates the connection itself is established and working fine.

I have tested with large data sets (lists in vMix with over a thousand items), but I'm seeing if perhaps there are other factors at play that may cause this issue.

**Comment by robsumm** [comment]
let me know if there are any details/logfiles I can send to help

**Comment by robsumm** [comment]
I Have loaded a new preset and the issue goes away but if I reload todays event it reappears so it is related to the Preset in vMix

**Comment by McHauge** [comment]
what preset, as a preset in vmix, or a preset in companion?

**Comment by robsumm** [comment]
in vmix

**Comment by McHauge** [comment]
is there something in that preset, that isn't in the one that works?

**Comment by thedist** [comment]
On the preset that doesn't work, if you're able could you please go to to http://localhost:8088/api (or if it's a remote machine, replace localhost with the vMix machine as appropriate), and copy what is shown and paste it somewhere such as https://pastebin.com/ for us to see.

If there's anything confidential, such as file names or input names feel free to edit it, just please keep it the same length and leave in any symbols incase it's a parsing error due to the length or a special character being present.

**Comment by robsumm** [comment]
They are totally different presets so yes loads of things. the one causing the problem is my "greenroom setup" but it works fine on the original CompanionPi. I have both Pi's connected at the moment if I look at the polling data on the edit button in companion when I have the greenroom preset loaded the new one stops at input6 (stopped at input5 once??) and the original pi shows everything.
Ill upload the api file in a minute

**Comment by robsumm** [comment]
https://www.dropbox.com/s/ctq7glmj9xumuse/rob%20-%20api.xml?dl=1
hope this is ok?

**Comment by thedist** [comment]
Thanks, I'll take a look at it and see what I can find.

**Comment by robsumm** [comment]
it is related to input 7, I have been reloading and deleting 1 input at a time, when 7 is deleted all works fine

**Comment by robsumm** [comment]
I inserted a timer as input 2 and now it stops at 2, so I assume it is related to the timer function in input 7, perhaps the colons are throwing something?

**Comment by robsumm** [comment]
sorry ignore that I got ahead of myself the timer in input 2 did not do what I thought

**Comment by robsumm** [comment]
Carriage return! it does not show on the API filbert input 7 has a carriage return in the text.
I have removed it and all is fine, I inserted a new text input and as soon as you enter a carriage return it breaks.

**Comment by thedist** [comment]
A carriage return could certainly be the issue at fault, and explain why when I inject that XML you linked it seemed to parse fine as that didn't have a carriage return in what I pasted into the module to test. It should be a simple fix if this is the root cause and we'll try to get it out soon.

**Comment by robsumm** [comment]
Thanks Guys appreciate your time on this and the app in general

Rob Summers

Sent from my iPhone

On 23 Nov 2020, at 21:42, Jeff Martin <notifications@github.com> wrote:

﻿

A carriage return could certainly be the issue at fault, and explain why when I inject that XML you linked it seemed to parse fine as that didn't have a carriage return in what I pasted into the module to test. It should be a simple fix if this is the root cause and we'll try to get it out soon.
