### ISSUE TITLE
vMix CutDirect option

### ISSUE THREAD

**Issue by DoumN** [bitfocus/companion-module-studiocoast-vmix#93]
Is it possible to add the CutDirect option of vMix, without transition in Companion. I didn't find it. The only option I found is "vMix: Transition - Send Input to Program". So, it cut, but create a transition with it. I want to have the same option as "vmix: Input - Send Input to Preview", but send it to Output (Program). If it already has an option for that, can you tell me how to do it please?

**Comment by McHauge** [comment]
@DoumN in the action "Transition - Send Input to Program" currently use "CutDirect" for Mix 1 and "Cut" for mix 2-4 since they don't support "CutDirect".

what you are looking after is the "ActiveInput" action, which is something we haven't used.
but you can use it via the "Custom Command" by typing: "ActiveInput &Input=x"

**Comment by DoumN** [comment]
Thanks for the answer. I’ll try it.
